import pandas as pd

# Full mapping of 640 specific job titles + "unemployed" to 30 broad categories + "Unemployed"
job_to_broad_category = {
    # Unemployed
    'unemployed': 'Unemployed',

    # 1. Agriculture & Horticulture
    'Amenity horticulturist': 'Agriculture & Horticulture',
    'Engineer, agricultural': 'Agriculture & Horticulture',
    'Agricultural engineer': 'Agriculture & Horticulture',
    'Farm manager': 'Agriculture & Horticulture',
    'Horticulturist, amenity': 'Agriculture & Horticulture',
    'Horticultural consultant': 'Agriculture & Horticulture',
    'Commercial horticulturist': 'Agriculture & Horticulture',
    'Fish farm manager': 'Agriculture & Horticulture',

    # 2. Arts, Design & Creative
    'Exhibition designer': 'Arts, Design & Creative',
    'Fashion designer': 'Arts, Design & Creative',
    'Set designer': 'Arts, Design & Creative',
    'Designer, ceramics/pottery': 'Arts, Design & Creative',
    'Designer, textile': 'Arts, Design & Creative',
    'Illustrator': 'Arts, Design & Creative',
    'Animator': 'Arts, Design & Creative',
    'Graphic designer': 'Arts, Design & Creative',
    'Designer, graphic': 'Arts, Design & Creative',
    'Fine artist': 'Arts, Design & Creative',
    'Artist': 'Arts, Design & Creative',
    'Make': 'Arts, Design & Creative',
    'Jewellery designer': 'Arts, Design & Creative',
    'Designer, industrial/product': 'Arts, Design & Creative',
    'Product designer': 'Arts, Design & Creative',
    'Ceramics designer': 'Arts, Design & Creative',
    'Designer, television/film set': 'Arts, Design & Creative',
    'Special effects artist': 'Arts, Design & Creative',
    'Designer, multimedia': 'Arts, Design & Creative',
    'Interior and spatial designer': 'Arts, Design & Creative',
    'Designer, interior/spatial': 'Arts, Design & Creative',
    'Designer, exhibition/display': 'Arts, Design & Creative',
    'Industrial/product designer': 'Arts, Design & Creative',
    'Designer, furniture': 'Arts, Design & Creative',
    'Furniture designer': 'Arts, Design & Creative',
    'Furniture conservator/restorer': 'Arts, Design & Creative',
    'Printmaker': 'Arts, Design & Creative',
    'Arboriculturist': 'Arts, Design & Creative',
    'Blown glass/stained glass designer': 'Arts, Design & Creative',  # If needed
    'Designer, blown glass/stained glass': 'Arts, Design & Creative',

    # 3. Engineering
    'Engineer, broadcasting (operations)': 'Engineering',
    'Engineer, building services': 'Engineering',
    'Engineer, water': 'Engineering',
    'Engineer, electronics': 'Engineering',
    'Civil engineer, contracting': 'Engineering',
    'Civil engineer, consulting': 'Engineering',
    'Engineer, production': 'Engineering',
    'Engineer, materials': 'Engineering',
    'Mechanical engineer': 'Engineering',
    'Chemical engineer': 'Engineering',
    'Mining engineer': 'Engineering',
    'Engineer, petroleum': 'Engineering',
    'Engineer, automotive': 'Engineering',
    'Engineer, biomedical': 'Engineering',
    'Engineer, land': 'Engineering',
    'Engineer, aeronautical': 'Engineering',
    'Engineer, structural': 'Engineering',
    'Engineer, chemical': 'Engineering',
    'Automotive engineer': 'Engineering',
    'Engineering geologist': 'Engineering',
    'Engineer, civil (consulting)': 'Engineering',
    'Engineer, drilling': 'Engineering',
    'Engineer, site': 'Engineering',
    'Engineer, technical sales': 'Engineering',
    'Engineer, control and instrumentation': 'Engineering',
    'Engineer, communications': 'Engineering',
    'Electronics engineer': 'Engineering',
    'Electrical engineer': 'Engineering',
    'Engineer, electrical': 'Engineering',
    'Energy engineer': 'Engineering',
    'Engineer, energy': 'Engineering',
    'Engineer, manufacturing': 'Engineering',
    'Manufacturing engineer': 'Engineering',
    'Metallurgist': 'Engineering',
    'Naval architect': 'Engineering',
    'Engineer, maintenance': 'Engineering',
    'Maintenance engineer': 'Engineering',
    'Engineer, maintenance (IT)': 'Engineering',
    'Engineer, manufacturing systems': 'Engineering',
    'Manufacturing systems engineer': 'Engineering',
    'Production engineer': 'Engineering',
    'Control and instrumentation engineer': 'Engineering',
    'Structural engineer': 'Engineering',
    'Contracting civil engineer': 'Engineering',
    'Aeronautical engineer': 'Engineering',

    # 4. Finance & Accounting
    'Accountant, chartered management': 'Finance & Accounting',
    'Accountant, chartered certified': 'Finance & Accounting',
    'Chartered certified accountant': 'Finance & Accounting',
    'Chartered public finance accountant': 'Finance & Accounting',
    'Accountant, chartered public finance': 'Finance & Accounting',
    'Chartered management accountant': 'Finance & Accounting',
    'Corporate treasurer': 'Finance & Accounting',
    'Financial controller': 'Finance & Accounting',
    'Financial planner': 'Finance & Accounting',
    'Financial adviser': 'Finance & Accounting',
    'Financial trader': 'Finance & Accounting',
    'Financial manager': 'Finance & Accounting',
    'Financial risk analyst': 'Finance & Accounting',
    'Investment analyst': 'Finance & Accounting',
    'Investment banker, corporate': 'Finance & Accounting',
    'Investment banker, operational': 'Finance & Accounting',
    'Futures trader': 'Finance & Accounting',
    'Equities trader': 'Finance & Accounting',
    'Bonds trader': 'Finance & Accounting',
    'Dealer': 'Finance & Accounting',
    'Financial controller': 'Finance & Accounting',
    'Tax inspector': 'Finance & Accounting',
    'Tax adviser': 'Finance & Accounting',
    'Senior tax professional/tax inspector': 'Finance & Accounting',
    'Chief Financial Officer': 'Finance & Accounting',
    'Chief Operating Officer': 'Finance & Accounting',
    'Chief Executive Officer': 'Finance & Accounting',  # Example classification
    'Chief Strategy Officer': 'Finance & Accounting',
    'Comptroller': 'Finance & Accounting',
    'Loss adjuster, chartered': 'Finance & Accounting',
    'Chartered loss adjuster': 'Finance & Accounting',
    'Accountant, chartered': 'Finance & Accounting',
    'Accounting technician': 'Finance & Accounting',

    # 5. Healthcare & Medicine
    'Occupational hygienist': 'Healthcare & Medicine',
    'Physiotherapist': 'Healthcare & Medicine',
    'Therapist, occupational': 'Healthcare & Medicine',
    'Therapist, art': 'Healthcare & Medicine',
    'Therapist, music': 'Healthcare & Medicine',
    'Nurse, learning disability': 'Healthcare & Medicine',
    'Nurse, adult': 'Healthcare & Medicine',
    "Nurse, children's": 'Healthcare & Medicine',
    'Nurse, mental health': 'Healthcare & Medicine',
    'Midwife': 'Healthcare & Medicine',
    'Speech and language therapist': 'Healthcare & Medicine',
    'Psychiatric nurse': 'Healthcare & Medicine',
    'Paramedic': 'Healthcare & Medicine',
    'Pathologist': 'Healthcare & Medicine',
    'Occupational psychologist': 'Healthcare & Medicine',
    'Psychologist, educational': 'Healthcare & Medicine',
    'Doctor, general practice': 'Healthcare & Medicine',
    'General practice doctor': 'Healthcare & Medicine',
    'Hospital doctor': 'Healthcare & Medicine',
    'Ophthalmologist': 'Healthcare & Medicine',
    'Oncologist': 'Healthcare & Medicine',
    'Neurosurgeon': 'Healthcare & Medicine',
    'Surgeon': 'Healthcare & Medicine',
    'Pharmacist, community': 'Healthcare & Medicine',
    'Pharmacist, hospital': 'Healthcare & Medicine',
    'Phytotherapist': 'Healthcare & Medicine',
    'Dietitian': 'Healthcare & Medicine',
    'Homeopath': 'Healthcare & Medicine',
    'Cytogeneticist': 'Healthcare & Medicine',
    'Embryologist, clinical': 'Healthcare & Medicine',
    'Dentist': 'Healthcare & Medicine',
    'Medical secretary': 'Healthcare & Medicine',
    'Medical sales representative': 'Healthcare & Medicine',
    'Medical physicist': 'Healthcare & Medicine',
    'Medical technical officer': 'Healthcare & Medicine',
    'Medical laboratory scientific officer': 'Healthcare & Medicine',
    'Physiological scientist': 'Healthcare & Medicine',
    'Medical illustrator': 'Healthcare & Medicine',
    'Pharmacologist': 'Healthcare & Medicine',
    'Haematologist': 'Healthcare & Medicine',
    'Immunologist': 'Healthcare & Medicine',
    'Audiological scientist': 'Healthcare & Medicine',
    'Music therapist': 'Healthcare & Medicine',
    'Community pharmacist': 'Healthcare & Medicine',
    'Paediatric nurse': 'Healthcare & Medicine',
    'Chiropodist': 'Healthcare & Medicine',
    'Podiatrist': 'Healthcare & Medicine',
    'Chiropractor': 'Healthcare & Medicine',
    'Herbalist': 'Healthcare & Medicine',
    'Health visitor': 'Healthcare & Medicine',
    'Therapeutic radiographer': 'Healthcare & Medicine',
    'Radiographer, diagnostic': 'Healthcare & Medicine',
    'Radiographer, therapeutic': 'Healthcare & Medicine',
    'Ambulance person': 'Healthcare & Medicine',

    # 6. Hospitality & Tourism
    'Restaurant manager': 'Hospitality & Tourism',
    'Hotel manager': 'Hospitality & Tourism',
    'Fast food restaurant manager': 'Hospitality & Tourism',
    'Restaurant manager, fast food': 'Hospitality & Tourism',
    'Conference centre manager': 'Hospitality & Tourism',
    'Travel agency manager': 'Hospitality & Tourism',
    'Barista': 'Hospitality & Tourism',
    'Holiday representative': 'Hospitality & Tourism',
    'Tour manager': 'Hospitality & Tourism',
    'Tourism officer': 'Hospitality & Tourism',
    'Theme park manager': 'Hospitality & Tourism',
    'Passenger transport manager': 'Hospitality & Tourism',

    # 7. Information Technology
    'Multimedia specialist': 'Information Technology',
    'IT consultant': 'Information Technology',
    'IT technical support officer': 'Information Technology',
    'Information systems manager': 'Information Technology',
    'Data scientist': 'Information Technology',
    'Database administrator': 'Information Technology',
    'Systems developer': 'Information Technology',
    'Systems analyst': 'Information Technology',
    'Network engineer': 'Information Technology',
    'Applications developer': 'Information Technology',
    'Programmer, applications': 'Information Technology',
    'Programmer, systems': 'Information Technology',
    'Programmer, multimedia': 'Information Technology',
    'Multimedia programmer': 'Information Technology',
    'IT trainer': 'Information Technology',
    'IT sales professional': 'Information Technology',
    'Games developer': 'Information Technology',
    'Computer games developer': 'Information Technology',
    'Software engineer': 'Information Technology',
    'Web designer': 'Information Technology',

    # 8. Law & Legal Services
    'Legal executive': 'Law & Legal Services',
    'Barrister': 'Law & Legal Services',
    'Lawyer': 'Law & Legal Services',
    'Solicitor': 'Law & Legal Services',
    'Solicitor, Scotland': 'Law & Legal Services',
    'Licensed conveyancer': 'Law & Legal Services',
    "Barrister's clerk": 'Law & Legal Services',
    'Chartered legal executive (England and Wales)': 'Law & Legal Services',
    'Armed forces training and education officer': 'Law & Legal Services',  # Example if needed
    'Patent attorney': 'Law & Legal Services',
    'Patent examiner': 'Law & Legal Services',
    'Trade mark attorney': 'Law & Legal Services',
    'Tax inspector': 'Law & Legal Services',
    'Legal secretary': 'Law & Legal Services',

    # 9. Education & Academia
    'Teacher, secondary school': 'Education & Academia',
    'Teacher, early years/pre': 'Education & Academia',
    'Teacher, primary school': 'Education & Academia',
    'Early years teacher': 'Education & Academia',
    'Secondary school teacher': 'Education & Academia',
    'Higher education lecturer': 'Education & Academia',
    'Lecturer, higher education': 'Education & Academia',
    'Lecturer, further education': 'Education & Academia',
    'Further education lecturer': 'Education & Academia',
    'Teacher, adult education': 'Education & Academia',
    'Commissioning editor': 'Education & Academia',  # Could also be in Publishing/Media
    'Administrator, education': 'Education & Academia',
    'Academic librarian': 'Education & Academia',
    'English as a foreign language teacher': 'Education & Academia',
    'Teacher, English as a foreign language': 'Education & Academia',
    'English as a second language teacher': 'Education & Academia',
    'Special educational needs teacher': 'Education & Academia',
    'Professor Emeritus': 'Education & Academia',
    'Associate Professor': 'Education & Academia',
    'Higher education careers adviser': 'Education & Academia',

    # 10. Media & Publishing
    'Editor, film/video': 'Media & Publishing',
    'Film/video editor': 'Media & Publishing',
    'Editorial assistant': 'Media & Publishing',
    'Magazine features editor': 'Media & Publishing',
    'Editor, magazine features': 'Media & Publishing',
    'Magazine journalist': 'Media & Publishing',
    'Journalist, magazine': 'Media & Publishing',
    'Journalist, newspaper': 'Media & Publishing',
    'Newspaper journalist': 'Media & Publishing',
    'Journalist, broadcasting': 'Media & Publishing',
    'Broadcast journalist': 'Media & Publishing',
    'Proofreader': 'Media & Publishing',
    'Publishing copy': 'Media & Publishing',
    'Publishing rights manager': 'Media & Publishing',
    'Public relations account executive': 'Media & Publishing',  # Could be Marketing
    'Public relations officer': 'Media & Publishing',
    'Press sub': 'Media & Publishing',
    'Press photographer': 'Media & Publishing',
    'Bookseller': 'Media & Publishing',
    'Programme researcher, broadcasting/film/video': 'Media & Publishing',
    'Video editor': 'Media & Publishing',
    'Production assistant, radio': 'Media & Publishing',
    'Producer, radio': 'Media & Publishing',
    'Media planner': 'Media & Publishing',
    'Media buyer': 'Media & Publishing',
    'Television production assistant': 'Media & Publishing',
    'Television/film/video producer': 'Media & Publishing',
    'Producer, television/film/video': 'Media & Publishing',
    'Radio broadcast assistant': 'Media & Publishing',
    'Radio producer': 'Media & Publishing',
    'Runner, broadcasting/film/video': 'Media & Publishing',
    'Location manager': 'Media & Publishing',
    'Lighting technician, broadcasting/film/video': 'Media & Publishing',
    'Sound technician, broadcasting/film/video': 'Media & Publishing',
    'Broadcast presenter': 'Media & Publishing',
    'Television floor manager': 'Media & Publishing',
    'Camera operator': 'Media & Publishing',
    'Television camera operator': 'Media & Publishing',
    'Gaffer': 'Media & Publishing',
    'Best boy': 'Media & Publishing',
    'Presenter, broadcasting': 'Media & Publishing',

    # 11. Science & Research
    'Research scientist (maths)': 'Science & Research',
    'Research scientist (physical sciences)': 'Science & Research',
    'Scientist, research (physical sciences)': 'Science & Research',
    'Scientist, research (maths)': 'Science & Research',
    'Research scientist (medical)': 'Science & Research',
    'Scientist, research (medical)': 'Science & Research',
    'Scientist, biomedical': 'Science & Research',
    'Clinical research associate': 'Science & Research',
    'Scientist, forensic': 'Science & Research',
    'Forensic scientist': 'Science & Research',
    'Research scientist (life sciences)': 'Science & Research',
    'Scientist, research (life sciences)': 'Science & Research',
    'Data processing manager': 'Science & Research',
    'Statistician': 'Science & Research',
    'Physicist, medical': 'Science & Research',
    'Biochemist, clinical': 'Science & Research',
    'Microbiologist': 'Science & Research',
    'Ecologist': 'Science & Research',
    'Astronomer': 'Science & Research',
    'Immunologist': 'Science & Research',
    'Marine scientist': 'Science & Research',
    'Oceanographer': 'Science & Research',
    'Scientist, marine': 'Science & Research',
    'Seismic interpreter': 'Science & Research',
    'Geoscientist': 'Science & Research',
    'Geochemist': 'Science & Research',
    'Hydrogeologist': 'Science & Research',
    'Hydrologist': 'Science & Research',
    'Soil scientist': 'Science & Research',
    'Geological information systems officer': 'Science & Research',  # Could be GI
    'Archaeologist': 'Science & Research',
    'Geologist, wellsite': 'Science & Research',
    'Wellsite geologist': 'Science & Research',
    'Mudlogger': 'Science & Research',
    'Operations geologist': 'Science & Research',
    'Field seismologist': 'Science & Research',
    'Geophysicist/field seismologist': 'Science & Research',
    'Geophysical data processor': 'Science & Research',
    'Scientist, product/process development': 'Science & Research',
    'Product/process development scientist': 'Science & Research',
    'Scientist, clinical (histocompatibility and immunogenetics)':
        'Science & Research',
    'Clinical scientist, histocompatibility and immunogenetics':
        'Science & Research',
    'Clinical molecular geneticist': 'Science & Research',
    'Geneticist, molecular': 'Science & Research',
    'Plant breeder/geneticist': 'Science & Research',
    'Clinical biochemist': 'Science & Research',
    'Clinical cytogeneticist': 'Science & Research',

    # 12. Marketing & Advertising
    'Advertising copywriter': 'Marketing & Advertising',
    'Advertising account planner': 'Marketing & Advertising',
    'Advertising art director': 'Marketing & Advertising',
    'Advertising account executive': 'Marketing & Advertising',
    'Copywriter, advertising': 'Marketing & Advertising',
    'Marketing executive': 'Marketing & Advertising',
    'Sales promotion account executive': 'Marketing & Advertising',
    'Lobbyist': 'Marketing & Advertising',

    # 13. Sales & Retail
    'Buyer, retail': 'Sales & Retail',
    'Retail buyer': 'Sales & Retail',
    'Retail merchandiser': 'Sales & Retail',
    'Buyer, industrial': 'Sales & Retail',
    'Retail manager': 'Sales & Retail',
    'Sales executive': 'Sales & Retail',
    'Sales professional, IT': 'Sales & Retail',
    'Retail banker': 'Sales & Retail',
    'Merchandiser, retail': 'Sales & Retail',
    'Store manager': 'Sales & Retail',  # If it existed
    'Retail merchandiser': 'Sales & Retail',

    # 14. Human Resources
    'Personnel officer': 'Human Resources',
    'Human resources officer': 'Human Resources',
    'Training and development officer': 'Human Resources',
    'Recruitment consultant': 'Human Resources',

    # 15. Social & Community Services
    'Social worker': 'Social & Community Services',
    'Community development worker': 'Social & Community Services',
    'Youth worker': 'Social & Community Services',
    'Aid worker': 'Social & Community Services',
    'Counsellor': 'Social & Community Services',
    'Counselling psychologist': 'Social & Community Services',
    'Psychologist, counselling': 'Social & Community Services',
    'Psychotherapist': 'Social & Community Services',
    'Psychotherapist, child': 'Social & Community Services',
    'Psychotherapist, dance movement': 'Social & Community Services',
    'Dance movement psychotherapist': 'Social & Community Services',
    'Dramatherapist': 'Social & Community Services',
    'Therapist, drama': 'Social & Community Services',
    'Therapist, horticultural': 'Social & Community Services',
    'Therapist, nutritional': 'Social & Community Services',
    'Administrator, charities/voluntary organisations': 'Social & Community Services',
    'Charity officer': 'Social & Community Services',
    'Charity fundraiser': 'Social & Community Services',
    'Volunteer coordinator': 'Social & Community Services',
    'Ranger/warden': 'Social & Community Services',
    'Warden/ranger': 'Social & Community Services',
    'Probation officer': 'Social & Community Services',

    # 16. Government & Public Sector
    'Diplomatic Services operational officer': 'Government & Public Sector',
    'Administrator, Civil Service': 'Government & Public Sector',
    'Civil Service administrator': 'Government & Public Sector',
    'Civil Service fast streamer': 'Government & Public Sector',
    'Government social research officer': 'Government & Public Sector',
    'Local government officer': 'Government & Public Sector',
    'Administrator, local government': 'Government & Public Sector',
    'Public affairs consultant': 'Government & Public Sector',
    'Environmental health practitioner': 'Government & Public Sector',
    'Equality and diversity officer': 'Government & Public Sector',
    'Emergency planning/management officer': 'Government & Public Sector',
    'Administrator, sports': 'Government & Public Sector',  # Could go either way
    'Research officer, government': 'Government & Public Sector',
    'Housing manager/officer': 'Government & Public Sector',
    'Public librarian': 'Government & Public Sector',
    'Registrar': 'Government & Public Sector',  # If it existed
    'Commercial/residential surveyor': 'Government & Public Sector',
    'Tax inspector': 'Government & Public Sector',  # Also in Finance, but here as well

    # 17. Construction & Architecture
    'Architect': 'Construction & Architecture',
    'Architectural technologist': 'Construction & Architecture',
    'Building services engineer': 'Construction & Architecture',
    'Building surveyor': 'Construction & Architecture',
    'Surveyor, building': 'Construction & Architecture',
    'Surveyor, building control': 'Construction & Architecture',
    'Building control surveyor': 'Construction & Architecture',
    'Quantity surveyor': 'Construction & Architecture',
    'Surveyor, quantity': 'Construction & Architecture',
    'Planning and development surveyor': 'Construction & Architecture',
    'Surveyor, planning and development': 'Construction & Architecture',
    'Construction manager': 'Construction & Architecture',  # If it existed
    'Contractor': 'Construction & Architecture',
    'Estate agent': 'Construction & Architecture',
    'Estate manager/land agent': 'Construction & Architecture',

    # 18. Environment & Conservation
    'Conservation officer, nature': 'Environment & Conservation',
    'Nature conservation officer': 'Environment & Conservation',
    'Conservation officer, historic buildings': 'Environment & Conservation',
    'Historic buildings inspector/conservation officer': 'Environment & Conservation',
    'Environment consultant': 'Environment & Conservation',  # If needed
    'Environmental consultant': 'Environment & Conservation',
    'Environmental manager': 'Environment & Conservation',
    'Environmental education officer': 'Environment & Conservation',
    'Energy manager': 'Environment & Conservation',
    'Water engineer': 'Environment & Conservation',
    'Scientist, water quality': 'Environment & Conservation',
    'Water quality scientist': 'Environment & Conservation',
    'Rural practice surveyor': 'Environment & Conservation',
    'Surveyor, rural practice': 'Environment & Conservation',
    'Surveyor, hydrographic': 'Environment & Conservation',
    'Hydrographic surveyor': 'Environment & Conservation',
    'Surveyor, minerals': 'Environment & Conservation',
    'Minerals surveyor': 'Environment & Conservation',
    'Surveyor, mining': 'Environment & Conservation',
    'Mining engineer': 'Environment & Conservation',
    'Quarry manager': 'Environment & Conservation',
    'Operations geologist': 'Environment & Conservation',
    'Geographical information systems officer': 'Environment & Conservation',

    # 19. Logistics & Transportation
    'Passenger transport manager': 'Logistics & Transportation',
    'Logistics and distribution manager': 'Logistics & Transportation',
    'Freight forwarder': 'Logistics & Transportation',
    'Air broker': 'Logistics & Transportation',
    'Ship broker': 'Logistics & Transportation',
    'Transport planner': 'Logistics & Transportation',
    'Purchasing manager': 'Logistics & Transportation',
    'Outdoor activities/education manager': 'Logistics & Transportation',  # Could fit else
    'Warehouse manager': 'Logistics & Transportation',
    'Pilot, airline': 'Logistics & Transportation',
    'Airline pilot': 'Logistics & Transportation',
    'Cabin crew': 'Logistics & Transportation',
    'Air cabin crew': 'Logistics & Transportation',
    'Air traffic controller': 'Logistics & Transportation',

    # 20. Performing Arts & Entertainment
    'Theatre manager': 'Performing Arts & Entertainment',
    'Theatre director': 'Performing Arts & Entertainment',
    'Theatre stage manager': 'Performing Arts & Entertainment',
    'Stage manager': 'Performing Arts & Entertainment',
    'Actor': 'Performing Arts & Entertainment',
    'Dancer': 'Performing Arts & Entertainment',
    'Musician': 'Performing Arts & Entertainment',
    'Music tutor': 'Performing Arts & Entertainment',
    'Private music teacher': 'Performing Arts & Entertainment',
    'Teacher, music': 'Performing Arts & Entertainment',
    'Producer, television/film/video': 'Performing Arts & Entertainment',
    'Producer, radio': 'Performing Arts & Entertainment',
    'Armed forces operational officer': 'Performing Arts & Entertainment',  # Example classification
    'Telecommunications researcher': 'Performing Arts & Entertainment',

    # 21. Pharmaceutical & Biotech
    # (Many roles already in Healthcare & Medicine / Science & Research; add if distinct)

    # 22. Nonprofit & Charity
    'Arts development officer': 'Nonprofit & Charity',
    'Charity officer': 'Nonprofit & Charity',
    'Development worker, community': 'Nonprofit & Charity',
    'Development worker, international aid': 'Nonprofit & Charity',
    'International aid/development worker': 'Nonprofit & Charity',

    # 23. Administration
    'Administrator': 'Administration',
    'Office manager': 'Administration',
    'Secretary/administrator': 'Administration',
    'Secretary, company': 'Administration',
    'Personal assistant': 'Administration',

    # 24. Security & Law Enforcement
    'Police officer': 'Security & Law Enforcement',
    'Armed forces logistics/support/administrative officer': 'Security & Law Enforcement',
    'Armed forces technical officer': 'Security & Law Enforcement',
    'Prison officer': 'Security & Law Enforcement',
    'Firefighter': 'Security & Law Enforcement',
    'Security officer': 'Security & Law Enforcement',  # If it existed

    # 25. Sports & Fitness
    'Sports therapist': 'Sports & Fitness',
    'Sports coach': 'Sports & Fitness',
    'Sports administrator': 'Sports & Fitness',
    'Fitness centre manager': 'Sports & Fitness',
    'Therapist, sports': 'Sports & Fitness',
    'Sports development officer': 'Sports & Fitness',

    # 26. Manufacturing & Industrial
    # (Many roles covered in Engineering, but if separate needed)

    # 27. Consulting & Advisory
    'Management consultant': 'Consulting & Advisory',
    'Consulting civil engineer': 'Consulting & Advisory',
    'Operational researcher': 'Consulting & Advisory',
    'Risk analyst': 'Consulting & Advisory',
    'Risk manager': 'Consulting & Advisory',

    # 28. Real Estate & Property
    # (Estate agent and manager already placed, but if separate needed)

    # 29. Miscellaneous
    'Ranger/warden': 'Miscellaneous',
    'Sub': 'Miscellaneous',
    'Contractor': 'Miscellaneous',
    'Make': 'Miscellaneous',
    'Copy': 'Miscellaneous',

    # 30. Public Services (combining some roles that might overlap)
    'Health and safety inspector': 'Public Services',
    'Claims inspector/assessor': 'Public Services',
    'Emergency planning/management officer': 'Public Services',
    'Regulatory affairs officer': 'Public Services',
    'Energy manager': 'Public Services',
    'Commissioning editor': 'Public Services',  # Could be in Media or Education
}

# Example usage: assume we have a DataFrame df with a column named "job"
# df = pd.DataFrame({'job': ['Amenity horticulturist', 'unemployed', 'Engineer, automotive']})
def map_jobs_to_categories(df):
    # Map the "job" column to the new "broad_job_category" column
    df['broad_job_category'] = df['job'].map(job_to_broad_category).fillna('Other')